name: License
on:
  workflow_dispatch: {}
 
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - name: Request unity license
        id: license
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2021.3.0f1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.license.outputs.filePath }}
          path: ${{ steps.license.outputs.filePath }}
